### PR TITLE
Doorlock configuration API

### PR DESCRIPTION
**Pull request by imilicevic7**

### CODE REVIEW

**Comment by tskaard** [comment]
@alivinco what is your thoughts on this? It's only for Z-Wave, should it be in the door_lock service?

**Comment by bjhandeland** [comment]
@alivinco can you please check this.

**Review by bjhandeland — APPROVED** [review]
LGTM

**Comment by bjhandeland** [comment]
@eternalamenity can you check if this is still valid. If no, please close the PR.

**Comment by eternalamenity** [comment]
@bjhandeland closing as, set_configuration action for door locks was already added in https://github.com/futurehomeno/fimp-api/pull/57

**Pull request closed without merging**
